# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetingsystem', '0003_meeting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='end_time',
            new_name='endTime',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='start_time',
            new_name='startTime',
        ),
    ]
