# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingsystem', '0004_auto_20160816_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='title',
            field=models.CharField(default='Meeting', max_length=120),
            preserve_default=False,
        ),
    ]
