# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 21:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetingsystem', '0006_invitebox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitebox',
            name='invites',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='blocks',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), default=list, size=None),
        ),
    ]
