# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 22:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetingsystem', '0007_auto_20160816_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitebox',
            name='invites',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='blocks',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
