# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 23:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingsystem', '0008_auto_20160816_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteBox',
            fields=[
                ('employeeID', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('invites', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('employeeID', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('blocks', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
            ],
        ),
    ]
