# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetingsystem', '0009_invitebox_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InviteBox',
        ),
    ]
