# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingsystem', '0011_invite'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeID', models.CharField(db_index=True, max_length=20)),
                ('type', models.CharField(choices=[('B', 'Busy'), ('M', 'Meeting')], default='B', max_length=1)),
                ('meetingID', models.CharField(default='', max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
