# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingsystem', '0012_auto_20160818_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeblock',
            name='type',
            field=models.CharField(default='BUSY', max_length=1),
        ),
    ]
