# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingsystem', '0014_auto_20160818_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
