# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingsystem', '0015_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='isEmployee',
            field=models.BooleanField(default=False),
        ),
    ]
