# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingsystem', '0016_auto_20160828_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeblock',
            name='day',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='timeblock',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
